{% set version = "20260706" %}

package:
    name: backtrace
    version: {{ version }}

source:
    url: https://github.com/ianlancetaylor/libbacktrace/archive/6f8310e238fc3ce68f42f391cbe93fd156bb2c23.zip
    sha256: 0afc4411db6ca175706b2974e9630cc5a183907a04f744f4d97e11d5e11dae72

build:
    number: 0
    run_exports:
        - {{ pin_subpackage('backtrace', max_pin='x.x') }}
    skip: true  # [win]

requirements:
    build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - make       # [unix]
    host:
        - zlib

test:
    commands:
        - test -f ${PREFIX}/lib/libbacktrace.a
        - test -f ${PREFIX}/lib/libbacktrace.so     # [linux]
        - test -f ${PREFIX}/lib/libbacktrace.dylib  # [osx]
        - test -f ${PREFIX}/include/backtrace.h

about:
    home: https://github.com/ianlancetaylor/libbacktrace
    license: BSD-3-Clause
    summary: A C library that may be linked into a C/C++ program to produce symbolic backtraces
    license_file: LICENSE

extra:
    recipe-maintainers:
        - bluescarni
